### ISSUE TITLE
Suggestion: Allow for any URL to be input

### ISSUE THREAD

**Issue by bigredwill** [nwittwer/reflex#113]
I am developing a site locally and have an entry in my Hosts file for it so that I can access it via `sitename.local` (for example). This allows me to test authentication locally with how the project is setup.
```
127.0.0.1 sitename.local
```

Right now the [autoCorrectURL.js](https://github.com/nwittwer/reflex/blob/master/src/renderer/mixins/autoCorrectURL.js) mixin will prepend `https://` so the url becomes `https://sitename.local`.  

**Suggestion:** Don't auto correct urls.  I see this as a dev tool so it would be nice to not have it modify the url.  Thoughts?

**Comment by nwittwer** [comment]
Hey, Will! This is definitely worth looking into. 

To give you some background into the autoCorrectURL.js file, check out https://github.com/nwittwer/reflex/issues/73. The need for it comes from the UX in Chrome, where you can just type in a domain name (i.e. "google.com", and you expect Chrome to figure out the rest for you (append http/https://). Otherwise, the browser would just sit there, since there's not a correct URL. And manually typing it can feel a bit tedious compared to what users might expect.

I would imagine these to be the main use cases, in regards to protocols:
- http/https://
- file://
- custom

In your case, there doesn't need to be a protocol specified, right? sitename.local would be exactly where you want the browser to navigate to?

Not sure if this is the right solution, but one possibility would be to add an auto-suggest menu, also similar to what Chrome does when you start typing in the URL bar. It displays a list of Google search results, your recent history results, and a static option if you just want to search for the term. Similarly, maybe when you type in URL, like sitename.local, you could select whether to go directly to that URL or have it auto-append a protocol?

**Comment by bigredwill** [comment]
The protocol for my case is `http` as it's in local development.

A way around this would be to check first if there is a protocol specified.  If a protocol is specified, don't auto correct. If a protocol is not specified, then auto correct to attempt to resolve.

**Comment by nwittwer** [comment]
Sounds good, I think it's way better to default to `http` instead of `https`.

FYI I've added a test for autoCorrectURL.js [here](https://github.com/nwittwer/reflex/blob/dev/src/renderer/mixins/__test__/autoCorrectURL.test.js). Accessible by running `npm run test`.

**Comment by nwittwer** [comment]
@bigredwill Made a PR for this here: https://github.com/nwittwer/reflex/pull/132/files, will merge in the next 1-2 weeks if there's no concerns
