### ISSUE TITLE
when entering url without http/https, it doesnt work 

### ISSUE THREAD

**Issue by duydnguyen07** [nwittwer/reflex#73]
Maybe it would be nicer if the app just append those prefixes like the chrome browser do.

**Comment by nwittwer** [comment]
Thanks for the note @duydnguyen07. I agree, this is an expected behavior that would be nice to have.

To expand on this:

**Problem:**
URLs currently must include the full path (i.e. `https://github.com`). So a URL like `github.com` will not work.

**Expectation**
When someone types text into the URL bar and hits enter/return, they expect it to try and load the page (default to adding `http://`).

**Comment by nwittwer** [comment]
@duydnguyen07 Please review some test cases here: https://jsfiddle.net/nwittwer/xpvt214o/862976/ 
Is it better to default to http or https?
